### ISSUE TITLE
Allow longer arguments to -attribute in show lattice

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#1295]
Right now there's a 60 character limit on the length of an argument to `-attribute` for `show lattice`. Could you make that longer for cases where one might want to use a more complex expression? Maybe 256 or 512? It's this line: https://github.com/bmad-sim/bmad-ecosystem/blob/a3385e3436ceaa5325369460ad3233395061f14c/tao/code/tao_show_this.f90#L173C1-L173C53

**Comment by jsberg-bnl** [comment]
Here's the kind of crazy thing someone might do: 
```sho lat 0:q1ef_6 -at sqrt(20e-3*(beta_a-2*(s+l0i)*alpha_a+(s+l0i)^2*gamma_a))@f12.3```

**Comment by DavidSagan** [comment]
Done.

**Comment by mattsignorelli** [comment]
This is still not fixed it seems: https://github.com/bmad-sim/bmad-ecosystem/blob/6048d2ef8419517256ddca50cc394bace7a4b3ef/tao/code/tao_show_this.f90#L173
And I get problems once the character length goes over 60. For example with

```
show lat 10 -at (1+alpha.b^2)/beta.b*eta.b^2+2*alpha.b*eta.b*etap.b+beta.b*etap.b^2
```
 The 60 character limit ends at `(1+alpha.b^2)/beta.b*eta.b^2+2*alpha.b*eta.b*etap.b+beta.b*e` so in fact for the last term its just printing out `beta.b*e` where `e` is Euler's number

**Comment by DavidSagan** [comment]
Fixed.
