### ISSUE TITLE
Problem with radiation integral calc with field map

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1492]
I have a field map I am working on that causes problems with the radiation integral calculation in Tao. This seems to be the same sort of problem with the reference time calculation that was fixed a few weeks ago. It tries, and fails, to calculate radiation integrals. eventually the lattice will load, but this takes too long. I tried using the -no_rad_int and it does not fix this issue

Lattice and field map are attached

[rad_with_field_map.zip](https://github.com/user-attachments/files/20124496/rad_with_field_map.zip)

**Comment by DavidSagan** [comment]
I am getting the error:
```
[ERROR | 2025-MAY-15 12:34:26] grid_field_interpolate:
    3D GRID_FIELD INTERPOLATION INDEX OUT OF BOUNDS: I1 = 40 (POSITION =     0.040506)
    FOR ELEMENT: WIGG1                                     (289)
    PARTICLE POSITION:     0.020506    0.000000    0.113337
    PARTICLE WILL BE MARKED AS LOST
[ERROR | 2025-MAY-15 12:34:26] rk_adaptive_step:
    Problem with field calc. Tracked particle will be marked as dead.
[ERROR | 2025-MAY-15 12:34:26] make_mat6_tracking:
    PARTICLE LOST IN TRACKING CENTRAL PARTICLE. MATRIX NOT CALCULATED FOR ELEMENT: WIGG1
[MESSAGE | 2025-MAY-15 12:34:28] bmad_parser:
```
This can slow things down and should be fixed before further investigation.
Also: Your ran_seed number is too large for the standard Fortran integer*4 type. You need to reduce this.

**Comment by jeu8** [comment]
I took out the ran_seed, but this other error you are getting seems to be related my issue. I cut down the lattice to end after the first wiggler. I still get this error, despite the orbit being within the bounds of the field map. 

This seems similar to the issue with reference time calculation, although I do have that set manually in this lattice. Another odd behavior I have noticed is that this error only occurs if you do not currently have a digested file

[test_lattice.zip](https://github.com/user-attachments/files/20248901/test_lattice.zip)

**Comment by DavidSagan** [comment]
Fixed. `-no_rad_int` flag is now no longer ignored by the init code.
