### ISSUE TITLE
Closed orbit does not update with generalized gradient maps

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#506]
[ags_fieldscale.zip](https://github.com/bmad-sim/bmad-ecosystem/files/12704841/ags_fieldscale.zip)

Run Tao in the previous folder.

Snakes have `is_on = T`, but `field_scale = 0`.

The startup sequence is the following:
1. Set `field_scale = 1`
2. Show BPM data for closed orbit

You can see that the closed orbit is not re-calculated for the new _field_scale_, and that the orbit plot shows something which is not a closed orbit.

However, if the snake lattice element are digested with `field_scale = 1` then the closed orbit is calculated appropriately.

**Comment by DavidSagan** [comment]
Fixed PR #511

**Comment by eiad-hamwi** [comment]
Why is this closed? 
The issue was not fixed, and I'm not sure what PR 511 has to do with it.

**Comment by DavidSagan** [comment]
@eiad-hamwi It is fixed. I put the change in the CLASSE GitLab repo today and so for releases it will be in tonight's nightly release.

**Comment by eiad-hamwi** [comment]
Oh okay. Thank you! And sorry about that...
