### ISSUE TITLE
Element attributes not updating when using ramper element

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#916]
The ramper element does not update attributes if ramper is used in a looped tao script. Notice that the energy does not change when the gt* script is ran. 
[error-examp.zip](https://github.com/bmad-sim/bmad-ecosystem/files/15001558/error-examp.zip)

**Comment by DavidSagan** [comment]
Fixed. Problem was in `set ele` command where the value of `t` was being taken to be zero.

**Comment by henrylovelace3** [comment]
I still see the same behavior using the latest release bmad_dist_20240416-1. 

Tao> call gt_table_my_calc.tao 

Tao: show -write table_blue_041624.txt string #RHIC latttice
#RHIC latttice

Written to file: table_blue_041624.txt

Tao: show -append table_blue_041624.txt string #Gamma T => `1/sqrt(lat::momentum_compaction[end]|design)@@6`
#Gamma T => 23.4154

Written to file: table_blue_041624.txt

Tao: set symbolic_num gt = 1/sqrt(lat::momentum_compaction[end]|design)

Tao: show -append table_blue_041624.txt string #turn energy(GeV) gamma del_gamma gammat alpha0 alpha1 tune.a tune.b chrom.a chrom.b YO5_QGT6[k1l] YO5_QGT12[k1l] YI2_QGT5[k1l] YI3_QGT11[k1l] eta.a(max) eta.a(min)
#turn energy(GeV) gamma del_gamma gammat alpha0 alpha1 tune.a tune.b chrom.a chrom.b YO5_QGT6[k1l] YO5_QGT12[k1l] YI2_QGT5[k1l] YI3_QGT11[k1l] eta.a(max) eta.a(min)

Written to file: table_blue_041624.txt

Tao: set uni 1 one_turn_map_calc = f

Tao: set symbolic_num T2 = 11.0

Tao: set symbolic_num T4 = 15.0

Tao: set symbolic_num turn = ceiling((T4-T2)/lat::time[end])

Tao: !do i = 0, 312367, 100

Tao: do i = 0, 312367, 312367
Loop: i = 0

Tao: set symbolic_num t = 0*lat::time[end]+T2

Tao: set ele ramper::* time = t

Tao: show string `t`
11

Tao: set symbolic_num alpha_p = (1/sqrt(lat::momentum_compaction[end]))

Tao: show value 1/sqrt(alpha_p)
     2.0648502909206609E-01

Tao: show -append table_blue_041624.txt string 0 `ele::end[e_tot]/197*1e-9` `ele::end[e_tot]/183.433337044e9` `1/sqrt(alpha_p)-ele::end[e_tot]/183.433337044e9` `1/sqrt(alpha_p)` `alpha_p` `-0.5*alpha_p` `lat::tune.a[end]/twopi` `lat::tune.b[end]/twopi` `lat::chrom.a` `lat::chrom.b` `ele::bi5_QGT5[k1l]` `ele::bo6_QGT12[k1l]` `ele::bo2_QGT6[k1l]` `ele::bi4_QGT11[k1l]` `max(lat::eta.a[beg*:end])` `min(lat::eta.a[beg*:end])`
0 17.993630741017 19.324433132513 -19.11794810342 0.20648502909207 23.45432083102 -11.72716041551 28.237984906553 29.229002797823 -2.9055804084166 -2.9737573199284 -0.00038 0.00038 -0.00038 0.00038 1.7919143834163 -0.36131805255409

Written to file: table_blue_041624.txt

Tao: enddo
Loop: i = 312367

Tao: set symbolic_num t = 312367*lat::time[end]+T2

Tao: set ele ramper::* time = t

Tao: show string `t`
15.000011865354

Tao: set symbolic_num alpha_p = (1/sqrt(lat::momentum_compaction[end]))

Tao: show value 1/sqrt(alpha_p)
     2.0648502909206609E-01

Tao: show -append table_blue_041624.txt string 312367 `ele::end[e_tot]/197*1e-9` `ele::end[e_tot]/183.433337044e9` `1/sqrt(alpha_p)-ele::end[e_tot]/183.433337044e9` `1/sqrt(alpha_p)` `alpha_p` `-0.5*alpha_p` `lat::tune.a[end]/twopi` `lat::tune.b[end]/twopi` `lat::chrom.a` `lat::chrom.b` `ele::bi5_QGT5[k1l]` `ele::bo6_QGT12[k1l]` `ele::bo2_QGT6[k1l]` `ele::bi4_QGT11[k1l]` `max(lat::eta.a[beg*:end])` `min(lat::eta.a[beg*:end])`
312367 17.993630741017 19.324433132513 -19.11794810342 0.20648502909207 23.45432083102 -11.72716041551 28.237984906553 29.229002797823 -2.9055804084166 -2.9737573199284 -0.00038 0.00038 -0.00038 0.00038 1.7919143834163 -0.36131805255409

Written to file: table_blue_041624.txt

Tao: enddo

**Comment by DavidSagan** [comment]
Looks like the change was not in the Release. I have generated a new Release so try that.
